### ISSUE TITLE
Finding aid

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/CA_lib_oration#15]
- UCSB uses oad:has_findingAid
- UCSD uses dc:relation with ucsd:relatedResource range (relatedType = findingAid)

https://github.com/ucsdlib/CA_lib_oration/blob/c3f467f7ec5acff879d95a34a69852c232682602/object_properties.yml#L1784-L1788

**Comment by chrissyrissmeyer** [comment]
UCSB is fine with this change. 

@arwenhutt: When you get a chance, could you please confirm that this portion of the model is still correct for UCSD? If yes, please comment and close.

**Comment by arwenhutt** [comment]
@chrissyrissmeyer yes, this is still what we're planning on using.
