### ISSUE TITLE
Preferred citation

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/CA_lib_oration#18]
- UCSB uses rda:preferredCitation 
- UCSD uses bf:preferredCitation

https://github.com/ucsdlib/CA_lib_oration/blob/c3f467f7ec5acff879d95a34a69852c232682602/object_properties.yml#L869

**Comment by chrissyrissmeyer** [comment]
UCSB is fine with making this change.

@arwenhutt: Can you please confirm that this is still what UCSD wants to use and comment / close if it is?

**Comment by arwenhutt** [comment]
@chrissyrissmeyer yes, this is still what we're planning on using.
