### ISSUE TITLE
Venue

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/CA_lib_oration#23]
- UCSB uses mods:note with mods:noteGroupType = venue
- UCSD uses ucsd:venue

https://github.com/ucsdlib/CA_lib_oration/blob/c3f467f7ec5acff879d95a34a69852c232682602/object_properties.yml#L1109-L1112

**Comment by chrissyrissmeyer** [comment]
UCSB is fine with this change. (Although if we decide to adopt BIBFRAME note / note type, I'd like to talk about moving this from a local predicate to a BIBFRAME note. And, if we decide we are going to add an events class, does this go there instead?)

@arwenhutt: When you get a chance, could you please confirm that this portion of the model is still correct for UCSD? If yes, please comment and close.

**Comment by arwenhutt** [comment]
yep!
