### ISSUE TITLE
Related resource predicates not used by UCSB

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/CA_lib_oration#30]
Note about related resources
- UCSB links directly to related resources
- UCSD uses dc:relation in conjunction with related resource class for these relationships

Not used by UCSB
- relation
- area
- artifact
- basket
- depiction
- exhibit
- findingAid
- journalEntry
- locus
- newsRelease
- stratum

https://github.com/ucsdlib/CA_lib_oration/blob/c3f467f7ec5acff879d95a34a69852c232682602/object_properties.yml#L1784-L1790

**Comment by chrissyrissmeyer** [comment]
UCSB is fine with this change.

@arwenhutt: When you get a chance, could you please confirm that this portion of the model is still correct for UCSD? If yes, please comment and close.

**Comment by arwenhutt** [comment]
yep!
