### ISSUE TITLE
Temporal subjects

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/CA_lib_oration#40]
- UCSB has not yet implemented temporal subjects (is mapped to dc:temporal)
- UCSD uses dc:temporal with edm:TimeSpan range

https://github.com/ucsdlib/CA_lib_oration/blob/c3f467f7ec5acff879d95a34a69852c232682602/object_properties.yml#L136-L140

**Comment by chrissyrissmeyer** [comment]
I reviewed and can confirm that UCSB is willing to change our current model and adapt this. 

@arwenhutt: When you get a chance, could you please confirm that this portion of the model is still correct for UCSB? If yes, please comment and close.

**Comment by arwenhutt** [comment]
@chrissyrissmeyer yes, for now we are still planning to use this.
