### ISSUE TITLE
Genre/Form

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/CA_lib_oration#41]
- UCSB uses rda:formOfWork
- ~~UCSD maps all genre/forms to topic~~ UCSD has added bf:genreForm to model
https://github.com/ucsdlib/CA_lib_oration/blob/c3f467f7ec5acff879d95a34a69852c232682602/object_properties.yml#L1919-L1922

**Comment by chrissyrissmeyer** [comment]
**Chrissy Rissmeyer**
Sep 1, 2017
Note that I don't necessary endorse the use of this specific predicate, just that UCSB needs this property within our model.

**Arwen Hutt**
Sep 14, 2017
Add/keep in model. UCSD can just not use it.

**Comment by chrissyrissmeyer** [comment]
I still endorse selecting a new predicate, so am going to indicate that further discussion is needed.

**Comment by chrissyrissmeyer** [comment]
This works for UCSB -- our current genre/form predicate is not really appropriate for how we are using it. BIBFRAME's genre/form is in alignment with our practice. 

@arwenhutt: When you get a chance, could you please review to confirm that this portion of the model is still correct for UCSD? If yes, please comment and close.

**Comment by arwenhutt** [comment]
@chrissyrissmeyer Per local metadata policy decisions, UCSD will encode all genre/form headings in topic -> so whatever predicate you think fits your usage best is fine.
