### ISSUE TITLE
Title types not used by UCSB

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/CA_lib_oration#46]
Not currently used by UCSB
- title:part name (modsrdf:partName)
https://github.com/ucsdlib/CA_lib_oration/blob/c3f467f7ec5acff879d95a34a69852c232682602/object_properties.yml#L2109-L2112
- title:part number (modsrdf:partNumber)
https://github.com/ucsdlib/CA_lib_oration/blob/c3f467f7ec5acff879d95a34a69852c232682602/object_properties.yml#L2136-L2139
- title:subtitle (modsrdf:subTitle)
https://github.com/ucsdlib/CA_lib_oration/blob/c3f467f7ec5acff879d95a34a69852c232682602/object_properties.yml#L2163-L2166

**Comment by chrissyrissmeyer** [comment]
UCSB is fine with this change. 

@arwenhutt: When you get a chance, could you please confirm that this portion of the model is still correct for UCSD? If yes, please comment and close.

**Comment by arwenhutt** [comment]
Currently yes, it's correct.  I think we'd be open to revisiting title handling in general.
