### ISSUE TITLE
Type of model / type of resource

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/CA_lib_oration#47]
- ADRL has both an model type (fedora:hasModel) which calls ingest scripts, drives display behavior etc. and a type of resource expressed in the metadata (via dc:type with values from http://id.loc.gov/vocabulary/resourceTypes). The ADRL object type is not exposed to the end user and the resource type is not necessarily related to the object type (e.g., you can ingest text content via the image object ingest script)
- UCSD does not distinguish between model types; only resource types are used.

**Comment by chrissyrissmeyer** [comment]
UCSB is fine with making this change.

@arwenhutt: Can you please confirm that this is still what UCSD wants to use and comment / close if it is?

**Comment by arwenhutt** [comment]
@chrissyrissmeyer Yes, we have no plans to use object or model types.
