### ISSUE TITLE
Archival arrangement (physical)

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/CA_lib_oration#49]
- UCSB does not capture physical arrangement 
- UCSD uses note:location of originals for physical arrangement

https://github.com/ucsdlib/CA_lib_oration/blob/c3f467f7ec5acff879d95a34a69852c232682602/object_properties.yml#L731-L735

**Comment by chrissyrissmeyer** [comment]
UCSB is fine with this change. (Although if we decide to adopt BIBFRAME note / note type, I'd like to talk about moving this from a local predicate to a BIBFRAME note.)

@arwenhutt: When you get a chance, could you please confirm that this portion of the model is still correct for UCSD? If yes, please comment and close.

**Comment by arwenhutt** [comment]
@chrissyrissmeyer Yes, this is still correct!
